server:
  port: 8082
  #应用名称
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 124.221.120.16:8848
      username: nacos
      password: nacos
      namespace: public
      ephemeral: false  # 永久实例（挂掉也不会删掉）